### ISSUE TITLE
Error while trying to repair file

### ISSUE THREAD

**Issue by tobschn** [kichiki/finsta360#1]
Hi there,
I tried to repair a corrupted Insta350 ONE R file. I thought it should be possible to repair it with your tool. The following error was thrown:
`# 3) rebuilding moov from the sample tables
Traceback (most recent call last):
  File "D:/anypath/FixInsta360/finsta360.py", line 680, in recover_moov_from_sample_tables
    copy_atom_box('uuid', None, f_moov, f_dst, only_header=False)
  File "D:/anypath/FixInsta360/finsta360.py", line 494, in copy_atom_box
    if atom_type != target_type: raise ValueError(f'{target_type} not found but {atom_type}')
ValueError: uuid not found but trak`
Do you have any idee how to fix it or what the problem is? It could be possible that the tool is not compatible with the H.265 codec from the ONE R.

**Comment by Skorupa94** [comment]
I am receiving this same exact error. I am also using the Insta360 One R and am hoping I can get this to work.  Please advise!

> ########################################
> # 1) extracting reference moov from
>         VID_20200605_115607_00_004.insv
> 
> ########################################
> # 2) regenerate sample tables from mdat in
>         VID_20200605_154141_00_007.insv
> 
> ########################################
> # 3) rebuilding moov from the sample tables
> Traceback (most recent call last):
>   File "finsta360.py", line 1015, in <module>
>     finsta360(
>   File "finsta360.py", line 926, in finsta360
>     recover_moov_from_sample_tables(
>   File "finsta360.py", line 680, in recover_moov_from_sample_tables
>     copy_atom_box('uuid', None, f_moov, f_dst, only_header=False)
>   File "finsta360.py", line 494, in copy_atom_box
>     if atom_type != target_type: raise ValueError(f'{target_type} not found but {atom_type}')
> ValueError: uuid not found but trak

**Comment by Namias** [comment]
ME TOO!!!
I am receiving this same exact error. I am also using the Insta360 One R.

########################################
# 1) extracting reference moov from
        D:\DCIM\Camera01\VID_20201212_143636_00_095.insv

########################################
# 2) regenerate sample tables from mdat in
        D:\DCIM\Camera01\VID_20201212_152603_00_096.insv

########################################
# 3) rebuilding moov from the sample tables
Traceback (most recent call last):
  File "D:\DCIM\Camera01\finsta360.py", line 1015, in <module>
    finsta360(
  File "D:\DCIM\Camera01\finsta360.py", line 926, in finsta360
    recover_moov_from_sample_tables(
  File "D:\DCIM\Camera01\finsta360.py", line 680, in recover_moov_from_sample_tables
    copy_atom_box('uuid', None, f_moov, f_dst, only_header=False)
  File "D:\DCIM\Camera01\finsta360.py", line 494, in copy_atom_box
    if atom_type != target_type: raise ValueError(f'{target_type} not found but {atom_type}')
ValueError: uuid not found but trak

**Comment by gi0na** [comment]
Same error here, trying to repair a file from a ONE X2:
```
ValueError                                Traceback (most recent call last)
<ipython-input-19-9ae6acee5d0b> in <module>
----> 1 finsta360(
      2     './untitled folder/VID_20210306_131545_00_012.insv', # src
      3     './untitled folder/VID_20210225_193713_00_010.insv', # ref
      4     'finsta360_00_012.insv',
      5     verbose=True,

<ipython-input-11-051c95fa76b5> in finsta360(src_filename, ref_filename, dst_filename, verbose)
     58     print('########################################')
     59     print(f'# 3) rebuilding moov from the sample tables')
---> 60     recover_moov_from_sample_tables(
     61         ref_moov_filename,
     62         new_moov_filename,

<ipython-input-9-549fad9c8439> in recover_moov_from_sample_tables(ref_filename, dst_filename, mov_table, aac_table, full_copy, n_chunk, verbose)
    190 
    191         # uuid
--> 192         copy_atom_box('uuid', None, f_moov, f_dst, only_header=False)
    193 
    194 

<ipython-input-9-549fad9c8439> in copy_atom_box(target_type, target_size, f_src, f_dst, only_header)
      3 def copy_atom_box(target_type, target_size, f_src, f_dst, only_header=True):
      4     src_size, atom_type = read_atom_head(f_src)
----> 5     if atom_type != target_type: raise ValueError(f'{target_type} not found but {atom_type}')
      6 
      7     if target_size is None: target_size = src_size

ValueError: uuid not found but trak

```

**Comment by drew2323** [comment]
same error here, any clues?

**Comment by azzkhan** [comment]
Any updates on this by anyone?

**Comment by gitthangbaby** [comment]
i was looking for this kind of tool because of errors:
`demuxer parse asset failed: domain:com.insta360.bmg.avmedia, code:-2`
just to find out it's all happening because of regional characters in path. Same error as above anyways.

**Comment by netAction** [comment]
Same here, File from Insta360 X2:


C:\Users\schmi\OneDrive\Desktop\Videoretten>python finsta360.py -s VID_20220605_134145_00_023.insv -r VID_20220605_135052_00_024.insv -o VID_20220605_134145_00_023-heile.insv

########################################
# 1) extracting reference moov from
        VID_20220605_135052_00_024.insv

########################################
# 2) regenerate sample tables from mdat in
        VID_20220605_134145_00_023.insv

########################################
# 3) rebuilding moov from the sample tables
Traceback (most recent call last):
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\finsta360.py", line 1015, in <module>
    finsta360(
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\finsta360.py", line 926, in finsta360
    recover_moov_from_sample_tables(
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\finsta360.py", line 680, in recover_moov_from_sample_tables
    copy_atom_box('uuid', None, f_moov, f_dst, only_header=False)
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\finsta360.py", line 494, in copy_atom_box
    if atom_type != target_type: raise ValueError(f'{target_type} not found but {atom_type}')
ValueError: uuid not found but trak

**Comment by netAction** [comment]
After uncommenting line 640 `copy_atom_box('uuid', None, f_moov, f_dst, only_header=False)` the script runs without crash. I assume the file format simply does no longer contain an **uuid**.
But the resulting file is broken and can't be read in Insta360 Studio or any video player.
I assume the file format of our files is completely different to the files finsta360 is made for.
